"""
GCS storage client with signed URL generation.

Images are stored in a private GCS bucket and served to clients via
time-limited V4 signed URLs generated by the Cloud Run service account.

Local dev: if MEDIA_BUCKET_NAME is unset, image paths are returned as-is
(relative paths resolve against the frontend dev server static files).
"""

import os
from datetime import timedelta

import google.auth
import google.auth.transport.requests
from google.cloud import storage

_gcs_client: storage.Client | None = None
_credentials = None


def _get_credentials():
    global _credentials
    if _credentials is None:
        _credentials, _ = google.auth.default(
            scopes=["https://www.googleapis.com/auth/cloud-platform"]
        )
    return _credentials


def get_client() -> storage.Client:
    global _gcs_client
    if _gcs_client is None:
        _gcs_client = storage.Client(
            project=os.environ.get("GOOGLE_CLOUD_PROJECT"),
            credentials=_get_credentials(),
        )
    return _gcs_client


def generate_signed_url(object_path: str) -> str:
    """Generate a V4 signed URL for a private GCS object."""
    bucket_name = os.environ.get("MEDIA_BUCKET_NAME")
    ttl = int(os.environ.get("SIGNED_URL_TTL_MINUTES", "60"))

    credentials = _get_credentials()
    auth_req = google.auth.transport.requests.Request()
    if not credentials.valid:
        credentials.refresh(auth_req)

    client = get_client()
    bucket = client.bucket(bucket_name)
    blob = bucket.blob(object_path)

    sa_email = getattr(credentials, "service_account_email", None)
    token = getattr(credentials, "token", None)

    return blob.generate_signed_url(
        version="v4",
        expiration=timedelta(minutes=ttl),
        method="GET",
        service_account_email=sa_email,
        access_token=token,
    )


def resolve_image_url(path: str | None) -> str | None:
    """
    Resolve an image path to a URL suitable for the client.

    - Absolute URLs (http/https): returned unchanged (external or already signed).
    - Media bucket paths (img/... or /img/...): generates a signed URL when
      MEDIA_BUCKET_NAME is set; returns path with leading slash for local dev.
    - Other relative paths (e.g. /logo.png): returned unchanged — these resolve
      against the frontend SPA bucket and are not in the media bucket.
    - None / empty: returned as-is.
    """
    if not path:
        return path
    if path.startswith("http://") or path.startswith("https://"):
        return path

    clean_path = path.lstrip("/")
    if not clean_path.startswith("img/"):
        return path  # SPA-relative path, not a media bucket object

    bucket_name = os.environ.get("MEDIA_BUCKET_NAME")
    if not bucket_name:
        return f"/{clean_path}"

    return generate_signed_url(clean_path)
